<a href="https://colab.research.google.com/github/jeandersonbc/deep-learning-practicing/blob/master/Getting_Started_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
print(torch.cuda.is_available())
print(torch.rand(2, 2))

True
tensor([[0.9094, 0.1373],
        [0.2075, 0.0167]])


In [4]:
torch.__version__

'1.3.1'

In [9]:
A = torch.rand(1, 3)
print(A)

tensor([[0.3726, 0.5500, 0.8440]])


In [10]:
B = torch.rand(3, 1)
print(B)

tensor([[0.5717],
        [0.0568],
        [0.1625]])


In [16]:
(A @ B).item()

0.3813363313674927

Tensors can live in the CPU or GPU. PyTorch allows to transfer tensors among different devices as seen below:

In [17]:
A.device

device(type='cpu')

In [0]:
A_gpu = A.to('cuda')

In [20]:
A_gpu.device

device(type='cuda', index=0)

Some basic operations...

In [21]:
A.max()

tensor(0.8440)

In [22]:
A.max().item()

0.8439812064170837